### ISSUE TITLE
It doesn't work with another admin account

### ISSUE THREAD

**Issue by dmontesdrp** [nielsengelen/vbo365-rest#19]
the login does not work with a different administrator account

Any suggestion because in the company de administrator user is disable in all servers, please  help me

**Comment by nielsengelen** [comment]
Can you verify you can actually login with that account to the regular VBO console?

**Comment by dmontesdrp** [comment]
Yes, the account works correctly when I made login in the server and the console

**Comment by nielsengelen** [comment]
Best would be to check the RESTful API logs (can be found under C:\ProgramData\Veeam\Backup365\Logs) to see what the error might be. If you can log in to the console and the RESTful API service is correct setup (and allows tenants to authenticate), it should just work.

**Comment by paultimson** [comment]
Hi, rather than generate a separate issue, I'm having a similar issue on our lab. We have VBR and VBO365 installed on the same server have setup a tenant on the VBR under Cloud Connect, but can only log in with the Administrator account of the VBR/VBO server via the Linux portal. I also can find no /logs folder in the above location so I'm a little confused. 

I've setup the VBO365 to use my account and it backs up happily.

When we do log in as administrator we see the GUI but with ZERO organisations.... am I being stupid?

**Comment by nielsengelen** [comment]
Paul, you should see the organizations which have been added within the VBO console if you log in as a server admin. The logs folder is related to VBO365 and API calls. There should be a file called Veeam.Archiver.REST_... which contains the output on the calls being performed by the portal. Could you log in and afterward check the file if there is an error or update regarding the account used?

The portal does not interact with cloud connect tenants but with VBO tenants.

**Comment by paultimson** [comment]
Hi Niels, I removed and re-installed the entire product set, VBR, VBO and all the explorers as the logs indicated a mismatch in versions, and now I do wee my organisation when I log in as admin. So that's good news. The next issue I hit is that the Exchange, Sharepoint and OneDrive top menu's error as they cannot find VBO365\Exchange. If I edit the URL to add the .php extension it displays the Exchnage window but selecting my organisation on the left pane results in a further error 
I hope this picture uploads correctly of the error

![image](https://user-images.githubusercontent.com/48687219/55814156-ec4d2480-5ae5-11e9-840d-785489925da1.png)

**Comment by nielsengelen** [comment]
Make sure you enable mod rewrite as indicated in the readme file as this is needed to handle the pages.

**Comment by paultimson** [comment]
Hi Niels, it looks to me like it is but I'm chasing one of our guys who can confirm this for me. Thanks for being so responsive. The aim of this is for me to get this working and then hand it to our developers to say ok incorporate that into our generic portal. That wya they can expand on the features using all the API suite available. Much appreciated, thank you.

**Comment by nielsengelen** [comment]
I will close this issue for now. If you still can't get it to work with the mod rewrite module, just comment here again and I will do my best to find the solution.
