### ISSUE TITLE
Error starting restore session

### ISSUE THREAD

**Issue by miljw002** [nielsengelen/vbo365-rest#35]
I have successfully installed and configured it, however whenever I try and start any restore session I get the following error:

"Error starting restore session
Error: Restore session cannot be created."

I get this for OneDrive, Exchange, and SharePoint.

All the other functionality appears to be working. I can see the backup repos, users, licenses, jobs etc.

**Comment by nielsengelen** [comment]
Did you install the explorers correctly? Which vbo version are you running?

**Comment by Neelon** [comment]
Don't know if this is relevant to your issue, but I got this error after implementing a fix from Veeam support. Turned out that some files from the fix were locked.

To unblock the files open elevated Powershell and enter these cmd's:

Get-ChildItem -path "C:\Program Files\Veeam\Backup and Replication\Explorers\Exchange" | Unblock-File

Get-ChildItem -path "C:\Program Files\Veeam\Backup and Replication\Explorers\SharePoint" | Unblock-File

**Comment by miljw002** [comment]
Ahh, thank you. I think I know what I’ve done. When I used an earlier version VBO was on a server with a GUI. It’s now running on server core, which won’t support the explorers. Feeling a little like an idiot now.

**Comment by nielsengelen** [comment]
Good mention of running on Windows core. I may have to dig into a solution for this. Let me know if you need additional help or if I can close this issue once it is resolved.

**Comment by nielsengelen** [comment]
Closing as it seems resolved for now.
