### ISSUE TITLE
Browsing export to pst issue

### ISSUE THREAD

**Issue by gschnabel-itsavvy** [nielsengelen/vbo365-rest#40]
When browsing a list of mailboxes I want to download a whole mailbox to PST and the window to hit ok pops up quick and looks like it minimizes.  After this it takes me to download.php with a white screen.   Nothing seems to try to download.   I am however able to download msg items.   Perhaps this is not knowing what to expect.

**Comment by nielsengelen** [comment]
This is most likely related due to the size of the mailbox. How large is the mailbox in general? Can you also check the REST logs if the export actually runs fine (can be found in C:\ProgramData\Veeam\Backup365\Logs).

I don't know if u already tried the below:
**It is advised to increase or disable the PHP maximum execution time limit.** This can be modified in the php.ini file as described per [changing the maximum execution time limit](https://www.simplified.guide/php/increase-max-execution-time).
