### ISSUE TITLE
Exchange / OneDrive/SharePoint Links not working

### ISSUE THREAD

**Issue by miljw002** [nielsengelen/vbo365-rest#8]
Hi,

I've not undertaken a lot of troubleshooting yet, but I thought I'd quickly ask before I start.

I've successfully installed this on a Linux (CentOS 7) box, and I'm able to connect successfully to my VBO365 server etc.

All of the items on the menu to the left are working (Jobs/Org/Repo/proxy etc), and I can see jobs, run them etc.

When I click on any of the menu items at the top (Exchange/OneDrive/SharePoint) I get a 404/file not found. The link appears to be /exchange, rather than the exchange.php file I can see.

As a quick test, I try manually going to exchange.php, and it loads. I then see the tenant link on the left. If I click on it I get another 404/file not found. This time the URL is /exchange/XXXXXXX-XXXXX-XXXXXX where the XXXX are the org ID.

Have I missed a line of config somewhere, or is this a bug?

**Comment by nielsengelen** [comment]
Hi,

This is related due to htaccess controlling how the pages are rewritten. By default this is not enabled on Apache/httpd on Centos and needs to be modified. Please follow the guide on https://devops.profitbricks.com/tutorials/install-and-configure-mod_rewrite-for-apache-on-centos-7/ and let me know if this solves it.

I will make a note on this and improve the readme file. Thanks!

**Comment by miljw002** [comment]
Perfect - thanks for the quick response, and that's fixed it. I'd missed one step in that process.

**Comment by charris-crs** [comment]
Hello Niels
We have got the portal working but when we try to assess a users mailbox to restore we get an error:
The requested URL /exchange/xxx is not found on this server.
I believe this is related to certificates or .htaccess but cannot find enough info to work out which one.

In REST log file
29/03/2019 12:29:04    8 (8668) Certificate claims:
29/03/2019 12:29:04    8 (8668)   Veeam Software
29/03/2019 12:29:04    8 (8668) Validation failed. Certificate is not valid for host localhost
I believe this relates to the Veeam O365 Server rather than the portal server.
I have regenerated new certificates under General Options and used it for both REST API and Authentication Tabs in General Options – Have restarted services but the problem persists.

Any ideas re the certificates or is there an entry I need to make in .htaccess?

Many Thanks

Clive

**Comment by nielsengelen** [comment]
Clive, the htaccess which you should leverage for the rewrite rules is available in the base repository: https://github.com/nielsengelen/vbo365-rest/blob/master/.htaccess

This file rewrites everything as it should be (Exchange, OneDrive & SharePoint). 

The REST log is normally just a warning due to using a self-signed certificate.

**Comment by charris-crs** [comment]
Niels
Many thanks
I have used that and success at last.

Best regards

Clive


Clive Harris
Managed Services Consultant
Covenco Recovery Services

Mobile: +44
Direct Dial: +44 (0)01295 274937
Fax: +44 (0)1753 732500
Email: clive.harris@covenco-dr.co.uk<mailto:clive.harris@covenco-dr.co.uk>


For more information about Covenco Recovery Services please visit our website at http://www.covenco-dr.co.uk<http://www.covenco-dr.co.uk/>
Follow us on: LinkedIn<mhtml:file://C:/Users/User/AppData/Roaming/Microsoft/Signatures/Clive%20Harris.mht!https://www.linkedin.com/company/1228295?trk=tyah&trkInfo=clickedVertical%3Acompany%2CentityType%3AentityHistoryName%2CclickedEntityId%3Acompany_1228295%2Cidx%3A0> | Twitter<mhtml:file://C:/Users/User/AppData/Roaming/Microsoft/Signatures/Clive%20Harris.mht!https://twitter.com/CovencoDR>

[819EC020]
     [85F1BB2E]   [60027F6C]

Company Registration Number: 3059168
Head Office Address:  Unit 4, MXL Centre, Lombard Way, Banbury, OX16 4TJ

This e-mail communication does not create or vary any contractual relationship between Covenco Recovery Services Limited (CRS) and you. Internet communications are not secure and accordingly CRS does not accept any legal liability for the contents of this message. The contents of this e-mail are confidential to the intended recipient at the e-mail address to which it has been addressed. It may not be disclosed to or used by anyone other than this addressee, nor may it be copied in any way. If received in error, please contact CRS on the above office number quoting the name of the sender and the addressee and then delete it from your system. Please note that neither CRS nor the sender accepts any responsibility for viruses and it is your responsibility to scan the e-mail and attachments (if any).

Registered Address: 5 South Parade, Summertown, Oxford, OX2 7JL, United Kingdom
