### ISSUE TITLE
Month view

### ISSUE THREAD

**Issue by leonbollerup** [nielsengelen/vbo365-rest#82]
Hi there,

First of all - awesome work... i'm wondering if you could integrate something like this ? - Its a month view that gives you a quick view of how everything looks like.. similar to www.zimonitor.com have for Ahsay backups.

![image](https://user-images.githubusercontent.com/342217/101453929-67588500-3930-11eb-8720-b7a9937475dc.png)

**Comment by nielsengelen** [comment]
Hi, 

While I like this view, it is not something that I can copy easily. VBO doesn't provide information at this point in time on the daily backup size. Providing an "OK" per day is possible but requires an extra database and a script that performs daily checks for storing everything. All in all, it requires a deeper insight into the existing VBO backups which is not something that can be done today. 

I don't plan to add an external database to this portal due to several reasons such as which type to pick (MySQL/Postgres/...), security reasons, etc.

**Comment by leonbollerup** [comment]
Hi,

I know, its a view we have integrated in our VBO monitoring tool - and yes, it does require some extra logic.

a sqllite db wouldent be an option ?

**Comment by nielsengelen** [comment]
It would take some time to create this in general though. It could be an idea to have this as a standalone tool compared to adding it to the portal (but maybe the ability to just enable it if wanted) but as I mentioned before it's mostly the security part around writing things in a database which holds me back. I'm not an expert at all on that matter.

**Comment by leonbollerup** [comment]
I think our developer might be able to help you.. he is currently sick - but once he comes back i will discuss it with him.

If you want the help, maybe you could contact me on leon.bollerup @ netsolutions . se

**Comment by nielsengelen** [comment]
As this would require heavy customization with a database and storing data, I won't be adding this and close this request.
